#!/usr/bin/env bash

# add github token to existing git repo (every time I forget the syntax)
# usage: add-ght -t <token> -r <repo_name> [-u <username>]

# this script is just for me anyway really
username="danielRuebenacker"
token=""
repo_name=""

while getopts "u:t:r:" opt; do
  case $opt in
    u) 
		username="$OPTARG"
		;;
    t) 
		token="$OPTARG"
		;;
    r) 
		repo_name="$OPTARG"
		;;
    *) 
		echo "Usage: $0 -t <token> -r <repo_name> [-u <username>]" >&2
		exit 1
		;;
  esac
done

# check they are not null
if [ -z "$token" ] || [ -z "$repo_name" ]; then
	echo "Error: Please enter a valid token and repo name." >&2
	exit 1;
fi


URL="https://${token}@github.com/${username}/${repo_name}.git"

git remote add origin "$URL"

echo "added"
